// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kezmnmbvmudqthlvydcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtlem1ubWJ2bXVkcXRobHZ5ZGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDY3MjAsImV4cCI6MjA2NDA4MjcyMH0.Dk8o7gH_zK-pYaL1Kdw8JX-2y0Wljyvn7996D9P-9ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);